# syntax=docker/dockerfile:1
FROM python:3.7-alpine
ADD . /python_flask
WORKDIR /python_flask
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install psutil
EXPOSE 5000
